version: '3.8'

services:
  db:
    image: postgres:17
    container_name: kensuiou-db
    platform: linux/x86_64
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./kensuiou-db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      - ./kensuiou-db/scripts:/scripts

  web:
    build:
      context: ./kensuiou-nextjs
      dockerfile: Dockerfile
    container_name: kensuiou-nextjs
    platform: linux/x86_64
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  localserver:
    build:
      context: ./kensuiou-localserver
      dockerfile: Dockerfile
    container_name: kensuiou-localserver
    # platform: linux/x86_64
    restart: always
    ports:
      - "8765:8765"
    env_file:
      - .env
    volumes:
      - ./kensuiou-localserver:/app
    depends_on:
      - db

volumes:
  postgres_data: